# Generated by Django 6.0.6 on 2026-08-02 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_id', models.CharField(db_index=True, help_text="Clerk's user ID (the JWT 'sub' claim). Sole link to identity.", max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable flag for admin deactivation (FR-06). Not a Django auth flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_profile', serialize=False, to='interview_system.user')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Total years of professional experience.', null=True)),
                ('headline', models.CharField(blank=True, default='', help_text="A short professional headline (e.g. 'Senior Python Developer').", max_length=255)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter_profile', serialize=False, to='interview_system.user')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='recruiter/logos/')),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('company_size', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'recruiter profile',
                'verbose_name_plural': 'recruiter profiles',
                'db_table': 'recruiter_profiles',
            },
        ),
    ]
