# Generated by Django 6.0.6 on 2026-07-03 20:08

import django.db.models.deletion
import interview_system.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether the user has verified their email.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', interview_system.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Total years of professional experience.', null=True)),
                ('headline', models.CharField(blank=True, default='', help_text="A short professional headline (e.g. 'Senior Python Developer').", max_length=255)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='recruiter/logos/')),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('company_size', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'recruiter profile',
                'verbose_name_plural': 'recruiter profiles',
                'db_table': 'recruiter_profiles',
            },
        ),
    ]
