# Generated by Django 6.0.6 on 2026-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
