# Generated by Django 6.0.6 on 2026-08-16 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0003_resume_application_parsedresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('breakdown', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='interview_system.application')),
            ],
            options={
                'verbose_name': 'candidate score',
                'verbose_name_plural': 'candidate scores',
                'db_table': 'candidate_scores',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('DONE', 'Done')], default='SCHEDULED', max_length=10)),
                ('retell_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interview_system.application')),
            ],
            options={
                'verbose_name': 'interview',
                'verbose_name_plural': 'interviews',
                'db_table': 'interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='interview_system.interview')),
            ],
            options={
                'verbose_name': 'interview session',
                'verbose_name_plural': 'interview sessions',
                'db_table': 'interview_sessions',
            },
        ),
        migrations.CreateModel(
            name='FrameAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('gaze_direction', models.CharField(blank=True, max_length=50)),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('detected_objects', models.JSONField(default=list)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_analyses', to='interview_system.interviewsession')),
            ],
            options={
                'verbose_name': 'frame analysis',
                'verbose_name_plural': 'frame analyses',
                'db_table': 'frame_analyses',
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attention_pct', models.FloatField(blank=True, null=True)),
                ('look_away_count', models.PositiveIntegerField(default=0)),
                ('integrity_flags', models.JSONField(default=list)),
                ('emotion_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_analysis', to='interview_system.interviewsession')),
            ],
            options={
                'verbose_name': 'behavioral analysis',
                'verbose_name_plural': 'behavioral analyses',
                'db_table': 'behavioral_analyses',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interview_system.user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('BEHAVIORAL', 'Behavioral'), ('TECHNICAL', 'Technical'), ('SITUATIONAL', 'Situational')], max_length=15)),
                ('source', models.CharField(choices=[('GENERATED', 'Generated'), ('TEMPLATE', 'Template')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_system.interview')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_system.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_system.interviewsession')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'db_table': 'responses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight_match', models.FloatField(default=0)),
                ('weight_interview', models.FloatField(default=0)),
                ('weight_behavioral', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'scoring rubric',
                'verbose_name_plural': 'scoring rubrics',
                'db_table': 'scoring_rubrics',
                'indexes': [models.Index(fields=['active'], name='idx_rubric_active')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='interview_system.user')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'db_table': 'audit_log_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_audit_target'), models.Index(fields=['action'], name='idx_audit_action')],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status'], name='idx_interview_status'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['retell_session_id'], name='idx_interview_retell'),
        ),
        migrations.AddIndex(
            model_name='frameanalysis',
            index=models.Index(fields=['session', 'ts'], name='idx_frame_session_ts'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='idx_notif_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='idx_question_category'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['approved'], name='idx_question_approved'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['session'], name='idx_response_session'),
        ),
    ]
