# Generated by Django 6.0.6 on 2026-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0004_interview_analysis_scoring_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='PENDING', help_text='Pipeline state: PENDING → PARSED or FAILED.', max_length=10),
        ),
    ]
