# Generated by Django 6.0.6 on 2026-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0012_user_email_normalized_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='The original name of the uploaded file.', max_length=255),
        ),
    ]
