# Generated by Django 6.0.6 on 2026-10-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0013_resume_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
