# Generated by Django 6.0.6 on 2026-10-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0014_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
