# Generated by Django 6.0.6 on 2026-10-09 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0015_user_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('policy', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PARSING', 'Parsing'), ('MATCHING', 'Matching'), ('SCREENING', 'Screening'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('criteria_results', models.JSONField(default=list)),
                ('eligibility', models.CharField(blank=True, max_length=12)),
                ('outcome', models.CharField(blank=True, max_length=24)),
                ('reasons', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('recovery_action', models.CharField(blank=True, max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume_hash', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.CharField(default='gemini-v1', max_length=64)),
                ('matcher_version', models.CharField(blank=True, max_length=100)),
                ('apply_decision', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('from_status', models.CharField(max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_shortlist_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='non_pass_policy',
            field=models.CharField(choices=[('REVIEW', 'Hold for review'), ('REJECT', 'Reject definite failures')], default='REVIEW', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='screening_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='screening_policy_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='screening_threshold',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='resume',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_claim',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parser_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENED', 'Screened'), ('UNDER_REVIEW', 'Under review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEWED', 'Interviewed'), ('DECISION', 'Decision')], default='APPLIED', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('screening_threshold__gte', 0), ('screening_threshold__lte', 100)), name='job_screening_threshold_range'),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='interview_system.application'),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interview_system.resume'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interview_system.applicationassessment'),
        ),
        migrations.AddField(
            model_name='screeningevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview_system.user'),
        ),
        migrations.AddField(
            model_name='screeningevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_events', to='interview_system.application'),
        ),
        migrations.AddField(
            model_name='screeningevent',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview_system.applicationassessment'),
        ),
        migrations.AddIndex(
            model_name='applicationassessment',
            index=models.Index(fields=['status', 'next_attempt_at'], name='interview_s_status_b44cfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationassessment',
            constraint=models.UniqueConstraint(fields=('application', 'revision'), name='unique_assessment_revision'),
        ),
        migrations.AddConstraint(
            model_name='applicationassessment',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__isnull', True), models.Q(('match_score__gte', 0), ('match_score__lte', 100)), _connector='OR'), name='assessment_score_range'),
        ),
    ]
